---
- name: Create VMs
  hosts: hypervisor
  vars:
    guest_name: centos7
    img_user: centos
    domain: vm
    volume_pool: default
    libvirt_vm_uri: "qemu:///system"

    libvirt_host_networks:
      - name: br-vm
        mode: nat
        # bridge: virbr0
        mac: 52:54:00:d7:7d:83
        ip:
          address: 192.168.70.1
          netmask: 255.255.255.0
          dhcp:
            range:
              start: 192.168.70.1
              end: 192.168.70.254
            hosts:
              - name: 'vm1'
                mac: 52:54:00:8f:64:00
                ip: 192.168.70.100
              - name: vm2
                mac: 52:54:00:8f:64:01
                ip: 192.168.70.101

    libvirt_vms:
      - state: present
        name: 'vm1'
        memory_mb: 2048
        vcpus: 2
        #cpu_mode: host-passthrough #host-model
        volumes:
          - name: 'centos-vm-1'
            device: 'disk'
            format: 'qcow2'
            clone: 'dmrub-centos7.img'
            pool: 'default'
        interfaces:
          - network: 'br-vm'
            mac: 52:54:00:8f:64:00

      - state: present
        name: 'vm2'
        memory_mb: 1024
        vcpus: 1
        volumes:
          - name: 'centos-vm-2'
            clone: 'dmrub-centos7.img'
            device: 'disk'
            format: 'qcow2'
            pool: 'default'
        interfaces:
          - network: 'br-vm'
            mac: 52:54:00:8f:64:01
  tasks:
    - name: Create VM Networks
      import_role:
        name: libvirt-host

    - name: Create VMs
      import_role:
        name: libvirt-vm
